services:
  - type: web
    name: learnify-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn learnify.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: learnify.settings
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: "learnify.onrender.com"
