# Generated by Django 4.2.21 on 2025-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
