# Generated by Django 4.2.21 on 2025-07-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_renewal_plan_requested_user_renewal_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_change_count',
            field=models.IntegerField(default=0),
        ),
    ]
