# Generated by Django 4.2.21 on 2025-07-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_grade_change_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_grade_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
